apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "kubestapaivaa"
  description: "Paevoo paevoo"
  annotations:
    github.com/project-slug: outesting/kubestapaivaa
    backstage.io/techdocs-ref: dir:.
spec:
  type: repository
  lifecycle: experimental
  owner: "group:default/admin"
